<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <SonarQubeTestProject>false</SonarQubeTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="VirtoCommerce.Platform.Data" Version="3.1039.0" />
    <PackageReference Include="VirtoCommerce.Platform.Security" Version="3.1039.0" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\VirtoCommerce.SalesRep.Core\VirtoCommerce.SalesRep.Core.csproj" />
  </ItemGroup>
</Project>
