<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <SonarQubeTestProject>true</SonarQubeTestProject>
    <NoWarn>NU1608;xUnit1051</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="8.0.1">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="FluentAssertions" Version="7.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.9" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.4.0" />
    <PackageReference Include="SQLitePCLRaw.bundle_e_sqlite3" Version="3.0.4" />
    <PackageReference Include="VirtoCommerce.CartModule.Data" Version="3.1008.0" />
    <PackageReference Include="VirtoCommerce.CatalogModule.Data" Version="3.1032.0" />
    <PackageReference Include="VirtoCommerce.CustomerModule.Data" Version="3.1014.0" />
    <PackageReference Include="VirtoCommerce.LuceneSearchModule.Data" Version="3.1002.0" />
    <PackageReference Include="VirtoCommerce.OrdersModule.Data" Version="3.1010.0" />
    <PackageReference Include="VirtoCommerce.Platform.Caching" Version="3.1048.0" />
    <PackageReference Include="VirtoCommerce.Platform.Modules" Version="3.1048.0" />
    <PackageReference Include="VirtoCommerce.SearchModule.Core" Version="3.1004.0" />
    <PackageReference Include="VirtoCommerce.SearchModule.Data" Version="3.1004.0" />
    <PackageReference Include="VirtoCommerce.StoreModule.Core" Version="3.1006.0" />
    <PackageReference Include="VirtoCommerce.XOrder.Data" Version="3.1009.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.5">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="xunit.v3" Version="3.2.2" />
  </ItemGroup>
  <ItemGroup>
    <NuGetAuditSuppress Include="https://github.com/advisories/GHSA-pgww-w46g-26qg" />
  </ItemGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\VirtoCommerce.SalesRep.Core\VirtoCommerce.SalesRep.Core.csproj" />
    <ProjectReference Include="..\..\src\VirtoCommerce.SalesRep.Data\VirtoCommerce.SalesRep.Data.csproj" />
    <ProjectReference Include="..\..\src\VirtoCommerce.SalesRep.ExperienceApi\VirtoCommerce.SalesRep.ExperienceApi.csproj" />
    <ProjectReference Include="..\..\src\VirtoCommerce.SalesRep.Web\VirtoCommerce.SalesRep.Web.csproj" />
  </ItemGroup>
</Project>
